"""Added missing columns to posts

Revision ID: e884a628a93b
Revises: e70c7f66becb
Create Date: 2025-04-07 02:26:14.180207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e884a628a93b'
down_revision: Union[str, None] = 'e70c7f66becb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'like_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like_id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
